### ISSUE TITLE
Error generating the rtf of the Screening Report 

### ISSUE THREAD

**Issue by hormiai76** [ispyb/ISPyB#319]
Hi all,
I got the following errror generating the RTF version of the Screening Report.
Any suggestion?`
Regards,
Alberto Nardella

```
2018-06-15 17:35:57,492 ERROR [stderr] (default task-3) java.lang.ClassCastException: com.lowagie.text.Table cannot be cast to com.lowagie.text.SimpleTable

2018-06-15 17:35:57,500 ERROR [stderr] (default task-3) 	at com.lowagie.text.rtf.RtfMapper.mapElement(Unknown Source)

2018-06-15 17:35:57,503 ERROR [stderr] (default task-3) 	at com.lowagie.text.rtf.RtfWriter2.add(Unknown Source)

2018-06-15 17:35:57,506 ERROR [stderr] (default task-3) 	at com.lowagie.text.Document.add(Unknown Source)

2018-06-15 17:35:57,509 ERROR [stderr] (default task-3) 	at ispyb.client.mx.collection.PdfRtfExporter.setDetailSessionObjectTable(PdfRtfExporter.java:1414)

2018-06-15 17:35:57,514 ERROR [stderr] (default task-3) 	at ispyb.client.mx.collection.PdfRtfExporter.exportDetails(PdfRtfExporter.java:1270)

2018-06-15 17:35:57,518 ERROR [stderr] (default task-3) 	at ispyb.client.mx.collection.ExportDataCollectionAction.prepareSessionExport(ExportDataCollectionAction.java:1206)

2018-06-15 17:35:57,522 ERROR [stderr] (default task-3) 	at ispyb.client.mx.collection.ExportDataCollectionAction.exportSessionAsRtf(ExportDataCollectionAction.java:1115)

2018-06-15 17:35:57,526 ERROR [stderr] (default task-3) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2018-06-15 17:35:57,533 ERROR [stderr] (default task-3) 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

2018-06-15 17:35:57,560 ERROR [stderr] (default task-3) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

2018-06-15 17:35:57,569 ERROR [stderr] (default task-3) 	at java.lang.reflect.Method.invoke(Unknown Source)

2018-06-15 17:35:57,593 ERROR [stderr] (default task-3) 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:274)

2018-06-15 17:35:57,600 ERROR [stderr] (default task-3) 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:194)

2018-06-15 17:35:57,604 ERROR [stderr] (default task-3) 	at ispyb.client.mx.collection.ExportDataCollectionAction.execute(ExportDataCollectionAction.java:111)

2018-06-15 17:35:57,607 ERROR [stderr] (default task-3) 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:419)

2018-06-15 17:35:57,611 ERROR [stderr] (default task-3) 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:224)

2018-06-15 17:35:57,615 ERROR [stderr] (default task-3) 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1194)

2018-06-15 17:35:57,618 ERROR [stderr] (default task-3) 	at ispyb.client.security.SpecificActionServlet.process(SpecificActionServlet.java:127)

2018-06-15 17:35:57,622 ERROR [stderr] (default task-3) 	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)

2018-06-15 17:35:57,626 ERROR [stderr] (default task-3) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

2018-06-15 17:35:57,630 ERROR [stderr] (default task-3) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

2018-06-15 17:35:57,634 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)

2018-06-15 17:35:57,637 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)

2018-06-15 17:35:57,641 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)

2018-06-15 17:35:57,645 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)

2018-06-15 17:35:57,649 ERROR [stderr] (default task-3) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

2018-06-15 17:35:57,653 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)

2018-06-15 17:35:57,657 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)

2018-06-15 17:35:57,663 ERROR [stderr] (default task-3) 	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)

2018-06-15 17:35:57,667 ERROR [stderr] (default task-3) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

2018-06-15 17:35:57,670 ERROR [stderr] (default task-3) 	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51)

2018-06-15 17:35:57,674 ERROR [stderr] (default task-3) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)

2018-06-15 17:35:57,678 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)

2018-06-15 17:35:57,683 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56)

2018-06-15 17:35:57,689 ERROR [stderr] (default task-3) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)

2018-06-15 17:35:57,693 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)

2018-06-15 17:35:57,698 ERROR [stderr] (default task-3) 	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)

2018-06-15 17:35:57,702 ERROR [stderr] (default task-3) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

2018-06-15 17:35:57,705 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)

2018-06-15 17:35:57,708 ERROR [stderr] (default task-3) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

2018-06-15 17:35:57,713 ERROR [stderr] (default task-3) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

2018-06-15 17:35:57,717 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)

2018-06-15 17:35:57,721 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)

2018-06-15 17:35:57,725 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)

2018-06-15 17:35:57,728 ERROR [stderr] (default task-3) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)

2018-06-15 17:35:57,732 ERROR [stderr] (default task-3) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)

2018-06-15 17:35:57,736 ERROR [stderr] (default task-3) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)

2018-06-15 17:35:57,739 ERROR [stderr] (default task-3) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

2018-06-15 17:35:57,742 ERROR [stderr] (default task-3) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

2018-06-15 17:35:57,746 ERROR [stderr] (default task-3) 	at java.lang.Thread.run(Unknown Source)


```

**Comment by delageniere** [comment]
Hi Alberto,
I fixed a fug on the rtf/pdf generation, may be it is ok form you also ?

**Comment by hormiai76** [comment]
I will try the fix and return to you
Alberto

**Comment by hormiai76** [comment]
I applied the fix in our test environment but my issue is still there. It seems to be a different problem.
Have you tried to generate the RTF Screening Report of a session? Does it work for you? We use the ISPyB interface to genearte it but if you use EXI I suppose the result should be the same, an empty document.

**Comment by delageniere** [comment]
Hi Alberto,
The last pull request fixes this. The side effect is that the rtf report is a bit changed because we can not use "chunk" objects to build the rtf while it is ok with pdf.
Solange

**Comment by hormiai76** [comment]
Hi Solange,
You can close it. We are starting moving to EXI. We will assume that the RTF report is not working in the old ISPyB interface and we will make more efforts in the new EXI development instead of fighting with some legacy code.
Thank you
